"""Create initial tables

Revision ID: 3d578483e183
Revises: 67843a3d1976
Create Date: 2025-05-05 10:19:16.065577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d578483e183'
down_revision: Union[str, None] = '67843a3d1976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('alt_text', sa.String(length=255), nullable=True))
    op.add_column('post_images', sa.Column('caption', sa.String(length=512), nullable=True))
    op.add_column('post_images', sa.Column('image_metadata', sa.JSON(), nullable=True))
    op.add_column('posts', sa.Column('content_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_images')
    op.drop_column('post_images', 'image_metadata')
    op.drop_column('post_images', 'caption')
    op.drop_column('post_images', 'alt_text')
    # ### end Alembic commands ###
