"""make longitude latitude and type required in posts

Revision ID: c7a50cd3e22f
Revises: bd19058cba3b
Create Date: 2025-06-08 14:12:29.469137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7a50cd3e22f'
down_revision: Union[str, None] = 'bd19058cba3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_featured_posts_id', table_name='featured_posts')
    op.drop_table('featured_posts')
    op.alter_column('posts', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'type',
               existing_type=postgresql.ENUM('kultura', 'natura', 'sport', 'zabawa', name='posttype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'type',
               existing_type=postgresql.ENUM('kultura', 'natura', 'sport', 'zabawa', name='posttype'),
               nullable=True)
    op.alter_column('posts', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('posts', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('featured_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='featured_posts_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='featured_posts_pkey')
    )
    op.create_index('ix_featured_posts_id', 'featured_posts', ['id'], unique=False)
    # ### end Alembic commands ###
